version: "1"

services:
  next-app:
    container_name: next-app
    image: misakanetworks-frontend:${HOST_TYPE?-latest}}
    build:
      context: .
      dockerfile: /docker/prod.Dockerfile
    restart: always
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
