# name: Create and publish a Docker image

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# # Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
# env:
#   REGISTRY: registry.cn-shanghai.aliyuncs.com
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@master
#       - name: Log in to the Container registry
#         uses: aliyun/acr-login@v1
#         with:
#           region-id: cn-shanghai
#           access-key-id: ${{ secrets.DOCKER_USER_NAME }}
#           access-key-secret: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#       - name: Build and push Docker image
#         env:
#           IMAGE_TAG: ${{ steps.meta.outputs.tags }}
#         run: |
#           docker build -t registry.cn-shanghai.aliyuncs.com/misaka-private/${{ github.repository }}:$IMAGE_TAG .
#           docker push registry.cn-shanghai.aliyuncs.com/misaka-private/${{ github.repository }}:$IMAGE_TAG .
